- name: Configure VSCode
  osx_defaults:
    domain: com.microsoft.VSCode
    state: present
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  with_items:
    - { key: ApplePressAndHoldEnabled, type: boolean, value: false }
