module ZellijBundler
  class ConfigTemplate
    def self.generate(installed_plugins)
      output_dir = installed_plugins.first&.dig(:output) || './plugins'

      lines = []
      lines << '# Zellij Plugin Configuration'
      lines << '# Generated by zellij-bundler'
      lines << ''
      lines << 'default_layout "default"'
      lines << ''
      lines << 'plugins:'
      lines << '  # Add your plugins below'

      installed_plugins.each do |plugin|
        filename = plugin[:file]
        path = File.join(output_dir, filename)
        lines << "  - location: \"file:#{path}\""
      end

      lines.join("\n")
    end
  end
end
