- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - git:
        repo: https://github.com/anyenv/anyenv
        dest: ~/.anyenv
        update: yes

    - name: Ensure plugins directory of anyenv
      file:
        path: ~/.anyenv/plugins
        state: directory
        mode: 0755
        
    - name: Install envs
      shell: '(~/.anyenv/bin/anyenv version | grep {{ item }}) || ~/.anyenv/bin/anyenv install {{ item }}'
      with_items:
        - rbenv
        - nodenv
        - pyenv
        - goenv

    - name: Ensure plugin directories of envs
      file:
        path: ~/.anyenv/envs/{{ item }}/plugins
        state: directory
        mode: 0755
      with_items:
        - rbenv
        - nodenv
        - pyenv
        - goenv
        
    - git:
        repo: https://github.com/nodenv/nodenv-package-rehash
        dest: ~/.anyenv/envs/nodenv/plugins/nodenv-package-rehash
        update: yes

    - name: Install rehash hooks for nodenv
      shell: '~/.anyenv/envs/nodenv/bin/nodenv package-hooks install'

