- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Make ensure homebrew is installed
      shell: 'which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'

    - homebrew:
        state: present
        name:
          - anyenv
          - direnv
          - fish
          - fzf
          - ghq
          - git
          - hub
          - jq
          - neovim
          - tmux
          - tig
