- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - file:
        path: '~/.config'
        state: directory

    - file:
        src: '~/dotfiles/{{ item }}'
        dest: '~/.config/{{ item }}'
        state: link
      with_items:
        - nvim
        - nyaovim
        - fish
        - git
        - karabiner

    - file:
        src: '~/dotfiles/{{ item.src }}'
        dest: '~/{{ item.dest }}'
        state: link
      with_items:
        - { src: '.atom', dest: '.atom' }
        - { src: '.gitconfig', dest: '.gitconfig' }
        - { src: '.tmux.conf', dest: '.tmux.conf' }
        - { src: '.tmux', dest: '.tmux' }
        - { src: '.tigrc', dest: '.tigrc' }
        - { src: '.zazurc.json', dest: '.zazurc.json' }
        - { src: '.hotel', dest: '.hotel' }

