- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - file:
        src: '~/dotfiles/{{ item.src }}'
        dest: '~/{{ item.dest }}'
        state: link
      with_items:
        - { src: '.tmux.conf.osx', dest: '.tmux.conf.osx' }
    - name: Make packages latest
      package:
        name: '{{ item }}'
        state: latest
      with_items:
        - direnv
        - fzf
        - neovim
        - tmux
        - fish
        - ghq
        - jq
        - go
        - hub
        - reattach-to-user-namespace
        - tig

    - homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items:
        - caskroom/cask
        - caskroom/versions

    - name: Make homebrew cask packages installed
      homebrew_cask:
        name: '{{ item }}'
        state: present
      with_items:
        - atom
        - atom-beta
        - docker
        - dropbox
        - google-japanese-ime
        - hyperswitch
        - iterm2
        - karabiner-elements
        - keeweb
        - oni
        - sequel-pro
        - spectacle
        - slack
        - xquartz
        - zazu

