- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: apt
      when: ansible_pkg_mgr == "apt"
    - role: mac
      when: ansible_os_family == "Darwin"
    # - atom
    # - fish
    # - fonts
    - ssh_key
    - role: osx_defaults
      when: ansible_os_family == "Darwin"
