include_cookbook 'homebrew'

homebrew 'cmake'
homebrew 'direnv'
homebrew 'fish'
homebrew 'fzf'
homebrew 'gh'
homebrew 'ghq'
homebrew 'git'
homebrew 'hub'
homebrew 'jq'
homebrew 'icu4c'
homebrew 'mysql'
homebrew 'neovim'
homebrew 'pkg-config'
homebrew 'postgresql'
homebrew 'tig'
homebrew 'tmux'
homebrew 'yarn'
homebrew 'ansible'
homebrew 'wget'

include_cookbook 'anyenv'
include_cookbook 'asdf'
