- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Configure Dock
      osx_defaults:
        domain: com.apple.dock
        state: present
        key: '{{ item.key }}'
        type: '{{ item.type }}'
        value: '{{ item.value }}'
      with_items:
        - { key: autohide, type: boolean, value: true }
