- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Configure Finder
      osx_defaults:
        domain: com.apple.finder
        state: present
        key: '{{ item.key }}'
        type: '{{ item.type }}'
        value: '{{ item.value }}'
      with_items:
        - { key: AppleShowAllFiles, type: boolean, value: true }
