- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Configure Trackpad
      osx_defaults:
        domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
        state: present
        key: '{{ item.key }}'
        type: '{{ item.type }}'
        value: '{{ item.value }}'
      with_items:
        - { key: Clicking, type: integer, value: 1 }
