- name: 'Copy dotfiles'
  file:
    src: '~/dotfiles/{{ item.src }}'
    dest: '~/{{ item.dest }}'
    state: link
  with_items:
    - { src: '.tmux.conf.osx', dest: '.tmux.conf.osx' }

- name: Make ensure homebrew is installed
  shell: 'which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'

- name: Make packages latest
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - ansible
    - direnv
    - fzf
    - neovim
    - tmux
    - fish
    - ghq
    - jq
    - go
    - hub
    - reattach-to-user-namespace
    - tig

- homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - caskroom/cask
    - caskroom/versions

- name: Make homebrew cask packages installed
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
    - atom
    - atom-beta
    - docker
    - google-japanese-ime
    - google-backup-and-sync
    - google-cloud-sdk
    - hyperswitch
    - hyper
    - iterm2
    - karabiner-elements
    - keeweb
    - oni
    - postman
    - logitech-options
    - sequel-pro
    - spectacle
    - slack
    - visual-studio-code
    - xquartz
    - zazu
