source ~/.config/zsh/setup/homebrew.zsh
source ~/.config/zsh/setup/devbin.zsh
source ~/.config/zsh/setup/aqua.zsh
source ~/.config/zsh/setup/anyenv.zsh
source ~/.config/zsh/setup/asdf.zsh
source ~/.config/zsh/setup/mise.zsh
source ~/.config/zsh/setup/code.zsh
source ~/.config/zsh/setup/pnpm.zsh
source ~/.config/zsh/setup/opencode.zsh
source ~/.config/zsh/setup/docker.zsh
source ~/.config/zsh/setup/lmstudio.zsh
source ~/.config/zsh/setup/bun.zsh
