- name: Make ensure homebrew is installed
  shell: 'which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'

- name: Install homebrew packages
  homebrew:
    state: present
    name:
      - direnv
      - fish
      - fzf
      - ghq
      - git
      - hub
      - jq
      - neovim
      - tmux
      - tig
      - yarn
